DROP TABLE IF EXISTS RECIPES;

CREATE TABLE RECIPES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) DEFAULT NULL,
  ingredients JSON DEFAULT NULL,
  instructions JSON DEFAULT NULL,
  yield INT,
  prepTime FLOAT,
  userId INT
);